name: Triage Failures

on:
  workflow_run:
    workflows: ['**']
    types: [completed]

permissions:
  actions: write # required to re-run jobs

jobs:
  triage:
    uses: ./.github/workflows/reuse-triage-failures.yml
    with:
      workflow-run: "${{ toJson(github.event.workflow_run) }}"
